# ПРЕДИКТЫ С НЕУДАЛЁННЫМИ КОЛОНКАМИ ПОСЛЕ ТЕПЛОВОЙ КАРТЫ!!!

In [102]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [103]:
data = pd.read_csv('train.csv')
data.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [104]:
to_del = ['Profession', 'Academic Pressure', 'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction', 'id', 'Name']
data_new = data.drop(columns = to_del)
print(data_new.isna().sum())
print("""
    #################
    """)
print(data_new.info())

Gender                                   0
Age                                      0
City                                     0
Working Professional or Student          0
Sleep Duration                           0
Dietary Habits                           4
Degree                                   2
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         4
Family History of Mental Illness         0
Depression                               0
dtype: int64

    #################

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140700 entries, 0 to 140699
Data columns (total 12 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Gender                                 140700 non-null  object
 1   Age                                    140700 non-null  float64
 2   City                                   140700 non-null  object
 3   Working Professional or Student        140700 non-null  object
 4   Sleep Duration                         140700 non-null  object
 5   Dietary Habits                         140696 non-null  object
 6   Degree                                 140698 non-null  object
 7   Have you ever had suicidal thoughts ?  140700 non-null  object
 8   Work/Study Hours                       140700 non-null  float64
 9   Financial Stress                       140696 non-null  float64
 10  Family History of Mental Illness       140700 non-null  object
 11  Depression                             140700 non-null  int64
dtypes: float64(3), int64(1), object(8)
memory usage: 12.9+ MB
None

In [105]:
data_new['Dietary Habits'] = data_new['Dietary Habits'].fillna('0')
data_new['Degree'] = data_new['Degree'].fillna('B')
data_new['Financial Stress'] = data_new['Financial Stress'].fillna(3)
print(data_new.isna().sum())

Gender                                   0
Age                                      0
City                                     0
Working Professional or Student          0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [106]:
data_new_cat = data_new.copy()
data_new_cat['Gender'] = data_new['Gender'].astype('category').cat.codes
data_new_cat['City'] = data_new['City'].astype('category').cat.codes
data_new_cat['Working Professional or Student'] = data_new['Working Professional or Student'].astype('category').cat.codes
data_new_cat['Sleep Duration'] = data_new['Sleep Duration'].astype('category').cat.codes
data_new_cat['Dietary Habits'] = data_new['Dietary Habits'].astype('category').cat.codes
data_new_cat['Degree'] = data_new['Degree'].astype('category').cat.codes
data_new_cat['Have you ever had suicidal thoughts ?'] = data_new['Have you ever had suicidal thoughts ?'].astype('category').cat.codes
data_new_cat['Family History of Mental Illness'] = data_new['Family History of Mental Illness'].astype('category').cat.codes
data_new_cat.head(5)

,Gender,Age,City,Working Professional or Student,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,49.0,50,1,29,8,33,0,1.0,2.0,0,0
1,1,26.0,93,1,27,21,63,1,7.0,3.0,0,1
2,1,33.0,97,0,15,8,21,1,3.0,1.0,0,1
3,1,22.0,64,1,27,16,28,1,10.0,1.0,1,1
4,0,30.0,37,1,15,21,28,1,9.0,4.0,1,0

In [107]:
from imblearn.over_sampling import SMOTE
data_train = data_new_cat.copy()
# smote = SMOTE(sampling_strategy='auto', k_neighbors=1)
# X_resampled, y_resampled = smote.fit_resample(data_train.drop(columns='Depression'), data_train['Depression'])
# X_resampled['Depression'] = y_resampled
# data_train = X_resampled

In [108]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140700 entries, 0 to 140699
Data columns (total 12 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Gender                                 140700 non-null  int8
 1   Age                                    140700 non-null  float64
 2   City                                   140700 non-null  int8
 3   Working Professional or Student        140700 non-null  int8
 4   Sleep Duration                         140700 non-null  int8
 5   Dietary Habits                         140700 non-null  int8
 6   Degree                                 140700 non-null  int8
 7   Have you ever had suicidal thoughts ?  140700 non-null  int8
 8   Work/Study Hours                       140700 non-null  float64
 9   Financial Stress                       140700 non-null  float64
 10  Family History of Mental Illness       140700 non-null  int8
 11  Depression                             140700 non-null  int64
dtypes: float64(3), int64(1), int8(8)
memory usage: 5.4 MB

In [109]:
data_test = pd.read_csv("test.csv")
data_test.head(5)

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [110]:
data_test = data_test.drop(columns = ['Name', 'id'])
data_test.head()

,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [111]:
to_del = ['Profession', 'Academic Pressure', 'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction']
data_test_new = data_test.drop(columns = to_del)
print(data_test_new.isna().sum())

Gender                                   0
Age                                      0
City                                     0
Working Professional or Student          0
Sleep Duration                           0
Dietary Habits                           5
Degree                                   2
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
dtype: int64

In [112]:
data_test_new_cat = data_test_new.copy()
data_test_new_cat['Gender'] = data_test_new['Gender'].astype('category').cat.codes
data_test_new_cat['City'] = data_test_new['City'].astype('category').cat.codes
data_test_new_cat['Working Professional or Student'] = data_test_new['Working Professional or Student'].astype('category').cat.codes
data_test_new_cat['Sleep Duration'] = data_test_new['Sleep Duration'].astype('category').cat.codes
data_test_new_cat['Dietary Habits'] = data_test_new['Dietary Habits'].astype('category').cat.codes
data_test_new_cat['Degree'] = data_test_new['Degree'].astype('category').cat.codes
data_test_new_cat['Have you ever had suicidal thoughts ?'] = data_test_new['Have you ever had suicidal thoughts ?'].astype('category').cat.codes
data_test_new_cat['Family History of Mental Illness'] = data_test_new['Family History of Mental Illness'].astype('category').cat.codes
data_test_new_cat.head(5)

,Gender,Age,City,Working Professional or Student,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,1,53.0,67,1,25,12,53,0,9.0,3.0,1
1,0,58.0,25,1,25,12,16,0,6.0,4.0,0
2,1,53.0,21,1,16,12,12,1,12.0,4.0,0
3,0,23.0,47,0,27,12,35,1,10.0,4.0,0
4,1,47.0,22,1,16,12,28,1,3.0,4.0,0

In [113]:
data_test = data_test_new_cat

In [114]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(data_train.drop(columns = 'Depression'))
d1 = data_train.copy().drop(columns = 'Depression')
d1[d1.columns] = scaler.transform(data_train.drop(columns = 'Depression'))

In [130]:
X_train, X_test, y_train, y_test = train_test_split(d1, data_train['Depression'], test_size = 0.25)

In [131]:
model = LogisticRegression(penalty = 'l1', solver = 'liblinear').fit(X_train, y_train)

In [132]:
coefficients = model.coef_[0] #  coefficients of the features
coeff_df = pd.DataFrame({
    'Feature': data_train.drop(columns='Depression').columns,
    'Coefficient': coefficients
}) # coefficients with their corresponding feature

In [133]:
coeff_df = coeff_df.reindex(coeff_df.Coefficient.abs().sort_values(ascending = False).index)
coeff_df

                                  Feature  Coefficient
1                                     Age    -6.818664
7   Have you ever had suicidal thoughts ?     2.495594
9                        Financial Stress     2.111696
5                          Dietary Habits     1.865774
8                        Work/Study Hours     1.537059
3         Working Professional or Student    -1.464931
10       Family History of Mental Illness     0.199949
6                                  Degree     0.149029
4                          Sleep Duration     0.121991
2                                    City    -0.074297
0                                  Gender     0.005377

In [134]:
model.score(X_test, y_test)

0.9243781094527364

In [135]:
from sklearn.model_selection import GridSearchCV

In [136]:
model = LogisticRegression()
params = {'penalty':['l2'], 'solver': ['lbfgs', 'saga'], 'max_iter': [100, 150, 200, 250]}
gsv = GridSearchCV(model, params, verbose = 1)
gsv.fit(X_train, y_train)
estimator = gsv.best_estimator_

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] END .............max_iter=100, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END .............max_iter=100, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END .............max_iter=100, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=100, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END .............max_iter=100, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END ..............max_iter=100, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=100, penalty=l2, solver=saga; total time=   0.3s
[CV] END ..............max_iter=100, penalty=l2, solver=saga; total time=   0.3s
[CV] END ..............max_iter=100, penalty=l2, solver=saga; total time=   0.6s
[CV] END ..............max_iter=100, penalty=l2, solver=saga; total time=   0.5s
[CV] END .............max_iter=150, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END .............max_iter=150, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=150, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=150, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END .............max_iter=150, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END ..............max_iter=150, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=150, penalty=l2, solver=saga; total time=   0.3s
[CV] END ..............max_iter=150, penalty=l2, solver=saga; total time=   0.3s
[CV] END ..............max_iter=150, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=150, penalty=l2, solver=saga; total time=   0.4s
[CV] END .............max_iter=200, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=200, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=200, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=200, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END .............max_iter=200, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END ..............max_iter=200, penalty=l2, solver=saga; total time=   0.5s
[CV] END ..............max_iter=200, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=200, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=200, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=200, penalty=l2, solver=saga; total time=   0.3s
[CV] END .............max_iter=250, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=250, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=250, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=250, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END .............max_iter=250, penalty=l2, solver=lbfgs; total time=   0.0s
[CV] END ..............max_iter=250, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=250, penalty=l2, solver=saga; total time=   0.3s
[CV] END ..............max_iter=250, penalty=l2, solver=saga; total time=   0.3s
[CV] END ..............max_iter=250, penalty=l2, solver=saga; total time=   0.4s
[CV] END ..............max_iter=250, penalty=l2, solver=saga; total time=   0.4s

In [137]:
estimator.score(X_test, y_test)

0.9244349680170576

In [138]:
X_train, X_test, y_train, y_test = train_test_split(data_train.drop(columns='Depression'), data_train['Depression'], test_size = 0.25)

In [139]:
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings("ignore")

In [140]:
xgb_model = XGBClassifier()
xgb_params = {
            'device': ["cuda"],
            'classifier__n_estimators': [100, 200],
            'classifier__max_depth': [4, 5],
            'classifier__learning_rate': [0.01, 0.05, 0.1],
            'classifier__min_child_weight': [1, 2, 3],  # Helps prevent overfitting
            'classifier__max_delta_step': [0, 1]  # For stability
        }

xgb_gsv = GridSearchCV(xgb_model, xgb_params, verbose = 1)
xgb_gsv.fit(X_train, y_train)
xgb_estimator = xgb_gsv.best_estimator_

Fitting 5 folds for each of 72 candidates, totalling 360 fits

In [141]:
xgb_estimator = xgb_gsv.best_estimator_

In [142]:
xgb_estimator.score(X_test, y_test)

0.9221606254442075

In [143]:
d2 = data_test.copy()
d2[d2.columns] = scaler.transform(data_test)

In [150]:
pred = estimator.predict(d2)

In [151]:
data_test_to_sub = pd.read_csv('test.csv')

In [152]:
submission = pd.DataFrame({'id': [], 'Depression': []})
submission['id'] = data_test_to_sub['id']
submission['Depression'] = pred

In [153]:
submission.head(4)

       id  Depression
0  140700           0
1  140701           0
2  140702           0
3  140703           1

In [154]:
submission.to_csv('submission_LR.csv', index = False)

In [155]:
pred = xgb_estimator.predict(data_test)

In [156]:
data_test_to_sub = pd.read_csv('test.csv')

In [157]:
submission = pd.DataFrame({'id': [], 'Depression': []})
submission['id'] = data_test_to_sub['id']
submission['Depression'] = pred

In [158]:
submission.to_csv('submission_XGB.csv', index = False)

In [159]:
import lazypredict
from lazypredict.Supervised import LazyClassifier

In [162]:
clf = LazyClassifier(verbose=0,
                     ignore_warnings=True,
                     custom_metric=None,
                     predictions=False,
                     classifiers='all')

models, predictions = clf.fit(X_train, X_test, y_train, y_test)

 97%|███████████████████████████████████████████████████████████████████████████████▏  | 28/29 [05:34<00:44, 44.07s/it]

[LightGBM] [Info] Number of positive: 19177, number of negative: 86348
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003549 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 207
[LightGBM] [Info] Number of data points in the train set: 105525, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.181729 -> initscore=-1.504674
[LightGBM] [Info] Start training from score -1.504674

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [05:35<00:00, 11.58s/it]

In [169]:
print(models)

                               Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model
QuadraticDiscriminantAnalysis      0.91               0.89     0.89      0.92
NearestCentroid                    0.88               0.89     0.89      0.89
GaussianNB                         0.90               0.87     0.87      0.90
SGDClassifier                      0.92               0.87     0.87      0.92
LGBMClassifier                     0.92               0.87     0.87      0.92
XGBClassifier                      0.92               0.86     0.86      0.92
AdaBoostClassifier                 0.92               0.86     0.86      0.92
LinearSVC                          0.92               0.86     0.86      0.92
LogisticRegression                 0.92               0.86     0.86      0.92
CalibratedClassifierCV             0.92               0.86     0.86      0.92
LinearDiscriminantAnalysis         0.91               0.86     0.86      0.91
SVC                                0.92               0.86     0.86      0.92
RandomForestClassifier             0.92               0.85     0.85      0.92
ExtraTreesClassifier               0.92               0.85     0.85      0.92
KNeighborsClassifier               0.91               0.84     0.84      0.91
PassiveAggressiveClassifier        0.89               0.84     0.84      0.90
BaggingClassifier                  0.91               0.83     0.83      0.91
BernoulliNB                        0.90               0.83     0.83      0.90
RidgeClassifier                    0.91               0.83     0.83      0.91
RidgeClassifierCV                  0.91               0.83     0.83      0.91
Perceptron                         0.89               0.81     0.81      0.89
DecisionTreeClassifier             0.88               0.80     0.80      0.88
ExtraTreeClassifier                0.88               0.80     0.80      0.88
DummyClassifier                    0.82               0.50     0.50      0.74

                               Time Taken
Model
QuadraticDiscriminantAnalysis        0.14
NearestCentroid                      0.10
GaussianNB                           0.14
SGDClassifier                        0.27
LGBMClassifier                       0.98
XGBClassifier                        0.76
AdaBoostClassifier                   2.75
LinearSVC                            5.47
LogisticRegression                   0.16
CalibratedClassifierCV              20.33
LinearDiscriminantAnalysis           0.19
SVC                                273.28
RandomForestClassifier               8.72
ExtraTreesClassifier                 8.28
KNeighborsClassifier                10.36
PassiveAggressiveClassifier          0.22
BaggingClassifier                    2.12
BernoulliNB                          0.13
RidgeClassifier                      0.14
RidgeClassifierCV                    0.19
Perceptron                           0.22
DecisionTreeClassifier               0.39
ExtraTreeClassifier                  0.17
DummyClassifier                      0.08

In [164]:
from sklearn.ensemble import RandomForestClassifier

In [165]:
rfc_model = RandomForestClassifier()
rfc_params = {'max_depth':[2, 3, 4, 5, 6], 'min_samples_split':[2], 'n_estimators':[100, 200], 'criterion':['gini', 'entropy', 'log_loss']}
rfc_gsv = GridSearchCV(rfc_model, rfc_params, verbose = 1)
rfc_gsv.fit(X_train, y_train)
rfc_estimator = rfc_gsv.best_estimator_

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.6s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.0s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.0s
[CV] END criterion=gini, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.8s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=100; total time=   2.0s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.9s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=200; total time=   4.7s
[CV] END criterion=gini, max_depth=3, min_samples_split=2, n_estimators=200; total time=   4.2s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.5s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.4s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.5s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.5s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.5s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=200; total time=   6.5s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=200; total time=   7.8s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=200; total time=   7.7s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=200; total time=   6.3s
[CV] END criterion=gini, max_depth=4, min_samples_split=2, n_estimators=200; total time=   5.4s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.9s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.9s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.9s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   3.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=200; total time=   6.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.9s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.4s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=100; total time=   2.9s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.0s
[CV] END criterion=gini, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.3s
[CV] END criterion=entropy, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.9s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=200; total time=   4.0s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=entropy, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.2s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=entropy, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.7s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.7s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.7s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   3.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.4s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.4s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.4s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.1s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.1s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.2s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=entropy, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.6s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=log_loss, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.1s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.8s
[CV] END criterion=log_loss, max_depth=3, min_samples_split=2, n_estimators=200; total time=   3.9s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.4s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=100; total time=   2.3s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.5s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.6s
[CV] END criterion=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   4.5s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=log_loss, max_depth=5, min_samples_split=2, n_estimators=200; total time=   5.3s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.1s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=100; total time=   3.0s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.0s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.2s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.3s
[CV] END criterion=log_loss, max_depth=6, min_samples_split=2, n_estimators=200; total time=   6.1s

In [166]:
rfc_estimator.score(X_test, y_test)

0.9221606254442075

In [167]:
pred = rfc_estimator.predict(data_test)

In [168]:
data_test_to_sub = pd.read_csv('test.csv')
submission = pd.DataFrame({'id': [], 'Depression': []})
submission['id'] = data_test_to_sub['id']
submission['Depression'] = pred
submission.to_csv('submission_rfc.csv', index = False)